### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gabriel-maxx** [CMatri/Salient-Rootkit#1]
Hello, I would like to know how do I make it so that as soon as the driver is registered and started it automatically finds the name of the process that I specify in the code and hides it? what do i have to edit in the code?

**Comment by iammaguire** [comment]
I recommend you start at PID = 0, pslookuprocessbyid it and traverse the linked list until the name is equal to the process name you'd like to hide, and unlink it. You can do this right in the DriverEntry function if you'd like.

**Comment by gabriel-maxx** [comment]
> I recommend you start at PID = 0, pslookuprocessbyid it and traverse the linked list until the name is equal to the process name you'd like to hide, and unlink it. You can do this right in the DriverEntry function if you'd like.

but what if the process I want to hide changes the pid every time? so what is specified in the code would be invalid

**Comment by gabriel-maxx** [comment]
@CMatri is it possible to hide a service process based on the service name and not the process name or pid ?

**Comment by iammaguire** [comment]
In regard to the first question, you could start a thread that loops through PIDs every couple minutes and removes any that matches the pid. For the second one I'm pretty certain that the service should be listed in PsLookupProcessById, however if it isn't (dont have time to test it right now), you could reverse OpenSCManager to see what structures it accesses in order to figure out how to find the right calls to get the info in kernel mode.

**Comment by iammaguire** [comment]
The calls mentioned here would be a good place to start reversing https://stackoverflow.com/questions/7808085/how-to-get-the-status-of-a-service-programmatically-running-stopped

**Comment by gabriel-maxx** [comment]
@CMatri thanks
